command:
  - ${env}
  - python3
  - icebeem/simulations.py
method: grid
metric:
  goal: minimize
  name: train_loss
parameters:
  data_dim:
    value: 5
  n_segments:
    value: 10
  n_layers:
    values: [1] #[ 2,4 ]
  n_obs_per_seg:
    values: [100] #, 200, 500, 1000, 2000]
  data_seed:
    value: 1
  seed:
    values: [ 42, 64, 982, 5748, 23567, 8734, 564, 74452, 96, 26 ]
  use_sem:
    value: true
  chain:
    values: [true, false]
#  ivae:
  max_iter:
    value: 70000
  lr:
    value: 0.001
  cuda:
    value: false
  # IceBeem
  lr_flow:
    value: 0.00001
  lr_ebm:
    value: 0.0003
  n_layers_flow:
    value: 3 # make 5 for L=2 IMCA best perf
  ebm_hidden_size:
    values: [16, 32, 64] # make 16 for L=2 IMCA best perf
  use_strnn:
    values: [false, true]
