data_dim: 5
n_segments: 10
n_layers: [1] #[ 2,4 ]
n_obs_per_seg: [100] #, 200, 500, 1000, 2000]
data_seed: 1
use_sem: true
chain: true

ivae:
  max_iter: 70000
  lr: 0.001
  cuda: False

icebeem:
  lr_flow: 0.00001
  lr_ebm: 0.0003
  n_layers_flow: 3 # make 5 for L=2 IMCA best perf
  ebm_hidden_size: 16 # make 16 for L=2 IMCA best perf
  use_strnn: false
